# Example to load default page
default:
    url: /
    class: WebPage\DefaultWebPage\DefaultWebPage::indexAction
    method: POST

route1:
    url: /profile/{id}
    class: WebPage\DefaultWebPage\DefaultWebPage::indexAction
    params:
        id: '[0-9]'

route2:
    url: /profile/posts
    class: WebPage\DefaultWebPage\DefaultWebPage::indexAction
